
CREATE TABLE GALLERY(
	ID_GALERIA int(11) AUTO_INCREMENT,
	S_NOMBRE varchar(255),
	CONSTRAINT PK_GALERIA PRIMARY KEY(ID_GALERIA)
)CHARSET = 'UTF8' COMMENT = 'TABLA PARA LAS GALERIAS DE UN RESTAURANTE';

CREATE TABLE SLIDE(
	ID_SLIDE int(11) AUTO_INCREMENT,
	ID_GALERIA int(11) NOT NULL,
	S_TITLE varchar(255),
	N_ORDER int(11),
	CONSTRAINT PK_SLDIE PRIMARY KEY (ID_SLIDE),
	CONSTRAINT FK_SLIDE_GALLERY FOREIGN KEY (ID_GALERIA) REFERENCES GALLERY (ID_GALERIA)
) ENGINE = MyISAM CHARSET = 'UTF8' COMMENT = "TABLA PARA LOS SLIDE DE LAS GALERIAS"